version: '3.4'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
    - POSTGRES_DB=Docs
    - POSTGRES_USER=Tadius
    - POSTGRES_PASSWORD=4444
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432   
  pgadmin:
    container_name: hotdog
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tadius@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80
    volumes:
    - ./.containers/pgAdmin:/var/lib/pgadmin
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - database
    environment:
      DB_TYPE: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: Tadius
      DB_PASS: 4444
      DB_NAME: Docs
    restart: unless-stopped
    ports:
      - "80:3000"
volumes:
  pgdata:
